# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# --------------------------------------------------------------------------------------------------------------------------------------------------
#
# Konsilion - Licence juridique Creative Commons CC-BY-NC
# --------------------------------------------------------------------------------------------------------------------------------------------------



# NAVIGATION
# --------------------------------------------------------------------------------------------------------------------------------------------------

nav:

    - Accueil: pages/accueil.md
    
    - Ingénierie collaborative:

        - De quoi parlons nous ?: pages/presentation.md

        - Katalog - CMS: pages/katalog.md
        
    - Recherche & Développement:
        
        - Projets: katalog/projets/home.md

        - Tâches: katalog/taches/home.md
        
        - Ressources: katalog/ressources/home.md
        
    - À propos: pages/informations.md



# SITE INFORMATIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

site_name: Konsilion - Low-technologie
site_author: Nicolas Brémond
site_description: Développer, proposer et promouvoir la Low-technologie.


# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# --------------------------------------------------------------------------------------------------------------------------------------------------

theme:
    language: fr
    palette:
        primary: blue grey
        accent: green
        scheme: default
    logo: https://github.com/Konsilion/website/blob/master/media/logo.png?raw=true
    favicon: https://user-images.githubusercontent.com/99027754/209714307-ab199f0d-509b-404f-9dd8-d8bd8fb99e37.png
    name: material
    custom_dir: overrides
    features:
      - navigation.indexes
      - navigation.tracking
      - navigation.top



extra:
  generator: false
  katalog_repo: "https://github.com/konsilion/website"
  katalog_site: "https://konsilion.github.io/website"

# MENTIONS 
# --------------------------------------------------------------------------------------------------------------------------------------------------

copyright: Une plateforme open-source codé avec ❤ par Konsilion - Licence juridique Creative Commons CC-BY-NC 4.0 <br> Un grand merci à <u><a href="https://www.multi.coop/" target="_blank">multi</a></u> et <u><a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">mkdocs-material</a></u> pour le support technique 







# AUTRES PARAMETRES - Ne pas modifier
# --------------------------------------------------------------------------------------------------------------------------------------------------
plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
      
extra_css:
  - https://konsilion.github.io/katalog-setup/css/konsilion-datami.css
  - https://konsilion.github.io/katalog-setup/css/konsilion-mkdocs.css
  
extra_js:
  - https://kit.fontawesome.com/f9666d4f53.js
